name: Synchronize Remote Repositories
on:
  push:
    branches:
      - main

jobs:
  mirror:
    name: Synchronize Mirror Repository
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.MIRROR_REPO_SSH_KEY }}
      - name: Set up Git
        run: |
          git remote add mirror "$REMOTE"
          git fetch mirror
        env:
          REMOTE: ${{ secrets.MIRROR_REPO_GIT_REMOTE }}
      - name: Push
        run: git push mirror main
